### ISSUE TITLE
Exception after sending the application form (Enabled debug output)

### ISSUE THREAD

**Issue by zenoussi** [itx-informationssysteme/jobapplications#129] opened 2023-11-02 21:11 UTC
I get the following message in the ddev development environment, instead of the success page:

_(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Runtime Deprecation Notice: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/html/vendor/itx/jobapplications/Classes/ViewHelpers/Format/ReplaceStringViewHelper.php line 32_

- jobapplications 3.0.3
- TYPO3 12.4.7
- PHP 8.1.13

However, the emails are sent correctly (MailHog).  

Greetings
Ulli

**Comment by itx-benjamin-jasper** [comment] 2023-11-24 13:58
I can't reproduce this, can you tell me for which ViewHelper call (ideally which parameters) this occurs?

**Comment by zenoussi** [comment] 2023-11-27 21:01
Unfortunately, I don't know what you mean by ViewHelper call.
I use the following settings in the plugin [jobapplications_applicationform]:

```
[settings.successPage]: Bewerbung versendet [pages_244]
[settings.pageTitle]: %postingTitle%
[settings.emailSender]: hallo@foo.de
[settings.emailSenderName]: Handicap KG
[settings.sendEmailToContact]: [1]
[settings.sendEmailToApplicant]: [1]
[settings.sendEmailToApplicantSubject]: Ihr Interesse an der Handicap KG: %postingTitle%

[settings.sendEmailToApplicantText]:
Hallo %applicantFirstName% %applicantLastName%!
Ihre Bewerbungsunterlagen "%postingTitle%" schauen wir uns gerne aufmerksam an und kommen wieder auf Sie zu.

[settings.saveApplicationInBackend]: [0]
[settings.showSalarayExpectation]: [0]
[settings.showEarliestDateOfJoining]: [0]
[settings.showMessage]: [0]
[settings.linkPrivacy]: t3://page?uid=201
[settings.honeypot]: [1]
[pages]: Jobapplication [pages_243]
[recursive]: [0]
```

**Comment by itx-benjamin-jasper** [comment] 2023-11-30 08:54
What I meant was, to take a look at the ViewHelper inputs specifically for the `replacement` argument as that seems to be the one causing the crash.

Weirdly enough the ViewHelper should already have checked for null because all arguments are required... not sure whats happening there.

**Comment by benjasper** [comment] 2024-08-30 12:08
Let us know, whether this is still an issue for you. Closing it for now

**Closed by benjasper** 2024-08-30 12:08 UTC
Labels: potential bug
