### ISSUE TITLE
Route Enhancers lead to 404 error page

### ISSUE THREAD

**Issue by der-phillip** [itx-informationssysteme/jobapplications#31] opened 2021-02-24 14:42 UTC
After updating to the current version and including the routeEnhancers configuration, only the 404 error page appears for the two views.

Does anyone still have this error?

**Comment by peerlight** [comment] 2021-02-25 09:49
same issue here

then suddenly it worked ...

where / how did you import default.yaml?

**Comment by der-phillip** [comment] 2021-02-25 10:28
This is my content. It is a little different from the [original file](Configuration/Routes/Default.yaml), but it works in version 0.9.12. Now, in version 1.0.1 it doesn't.

I have added **limitToPages** and a new line before **routePath**.

```
routeEnhancers:
  JobapplicationsDetailView:
    type: Extbase
    limitToPages:
      - 286
    namespace: tx_jobapplications_detailview
    routes:
      -
        routePath: '/{slug}'
        _controller: 'Posting::show'
        _arguments:
          slug: posting
    defaultController: 'Posting::list'
    aspects:
      slug:
        type: PersistedAliasMapper
        tableName: tx_jobapplications_domain_model_posting
        routeFieldName: slug
  JobapplicationsApplicationForm:
    type: Extbase
    limitToPages:
      - 287
    namespace: tx_jobapplications_applicationform
    routes:
      -
        routePath: '/{slug}'
        _controller: 'Application::new'
        _arguments:
          slug: posting
    defaultController: 'Application::new'
    aspects:
      slug:
        type: PersistedAliasMapper
        tableName: tx_jobapplications_domain_model_posting
        routeFieldName: slug
```

**Comment by itx-benjamin-jasper** [comment] 2021-12-20 14:51
Closing this because I can't reproduce this. If this is still an issue please reopen.

**Closed by itx-benjamin-jasper** 2021-12-20 14:51 UTC
Labels: potential bug
